//! Build script: pre-parse mpron.txt into a sorted static array at compile time.
//!
//! This parses the Moby Pronunciator II dictionary (Windows-1252 encoded) and
//! generates `src/dict_data.rs` containing a sorted `&[(&str, &[&str])]` array.
//! At runtime, binary search provides O(log n) lookups with zero allocation.

use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mpron_path = manifest_dir.join("bin").join("mpron.txt");
    let out_path = manifest_dir.join("src").join("dict_data.rs");

    // Only regenerate if the dictionary changed
    println!("cargo:rerun-if-changed=bin/mpron.txt");
    println!("cargo:rerun-if-changed=build.rs");

    // Read the Windows-1252 encoded file
    let raw = fs::read(&mpron_path).expect("Failed to read mpron.txt");
    let (decoded, _, _) = encoding_rs::WINDOWS_1252.decode(&raw);
    let content = decoded.to_string();

    // Parse all entries
    let mut entries: Vec<(String, Vec<String>)> = Vec::new();

    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with(";;;") {
            continue;
        }

        // Find the first space, safely handling UTF-8 byte boundaries
        let space_byte_pos = match line.find(' ') {
            Some(p) => p,
            None => continue,
        };

        // Use char-based indexing to safely split at word boundary
        let word_part: String = line[..space_byte_pos].to_string();
        let pron_part = line[space_byte_pos + 1..].trim();

        // Extract word (strip optional /pos suffix), using char-based find
        let word = if let Some(slash_pos) = word_part.find('/') {
            word_part[..slash_pos].to_lowercase()
        } else {
            word_part.to_lowercase()
        };

        let phonemes = parse_pronunciation(pron_part);

        if phonemes.is_empty() {
            continue;
        }

        entries.push((word, phonemes));
    }

    // Sort entries for binary search
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate Rust source
    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — DO NOT EDIT\n");
    out.push_str("// Sorted Moby Pronunciator II entries for binary search.\n");
    out.push_str(
        "pub const DICT_ENTRIES: &[(&str, &[&str])] = &[\n",
    );

    for (word, phonemes) in &entries {
        out.push_str("    (\"");
        // Escape special characters in word
        for ch in word.chars() {
            escape_char(ch, &mut out);
        }
        out.push_str("\", &[");
        for (i, p) in phonemes.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push('"');
            for ch in p.chars() {
                escape_char(ch, &mut out);
            }
            out.push('"');
        }
        out.push_str("]),\n");
    }

    out.push_str("];\n");

    // Only write if content changed (avoids recompilation)
    let current = fs::read_to_string(&out_path).unwrap_or_default();
    if current != out {
        let mut f = fs::File::create(&out_path).expect("Failed to create dict_data.rs");
        f.write_all(out.as_bytes())
            .expect("Failed to write dict_data.rs");
        println!(
            "cargo:warning=Generated dict_data.rs with {} entries",
            entries.len()
        );
    }
}

fn escape_char(ch: char, out: &mut String) {
    match ch {
        '\\' => out.push_str("\\\\"),
        '"' => out.push_str("\\\""),
        '\n' => out.push_str("\\n"),
        '\r' => out.push_str("\\r"),
        '\t' => out.push_str("\\t"),
        _ => out.push(ch),
    }
}

/// Phoneme mapping table (same as in mpron.rs).
const NAKED_TO_XSAMPA: &[(&str, &str)] = &[
    ("Oi", "OI"),
    ("aU", "aU"),
    ("aI", "aI"),
    ("eI", "eI"),
    ("oU", "oU"),
    ("ju", "ju"),
    ("tS", "tS"),
    ("dZ", "dZ"),
    ("[@]", "@"),
    ("x", "x"),
    ("y", "y"),
    ("&", "{}"),
    ("-", "@"),
    ("@", "@"),
    ("A", "A"),
    ("D", "D"),
    ("E", "E"),
    ("I", "I"),
    ("N", "N"),
    ("O", "O"),
    ("S", "S"),
    ("T", "T"),
    ("U", "U"),
    ("i", "i"),
    ("j", "j"),
    ("u", "u"),
    ("b", "b"),
    ("d", "d"),
    ("f", "f"),
    ("g", "g"),
    ("h", "h"),
    ("k", "k"),
    ("l", "l"),
    ("m", "m"),
    ("n", "n"),
    ("p", "p"),
    ("r", "r"),
    ("s", "s"),
    ("t", "t"),
    ("v", "v"),
    ("w", "w"),
    ("z", "z"),
];

fn lookup_phoneme(id: &str) -> Option<&'static str> {
    for &(key, xsampa) in NAKED_TO_XSAMPA {
        if key == id {
            return Some(xsampa);
        }
    }
    None
}

fn split_slash_content(content: &str) -> Vec<String> {
    let cleaned: String = content
        .chars()
        .filter(|c| *c != '\'' && *c != ',')
        .collect();

    let mut result = Vec::new();
    let mut remaining = cleaned.as_str();

    // Build sorted list of multi-char identifiers, longest first
    let mut ids: Vec<&str> = NAKED_TO_XSAMPA.iter().map(|(k, _)| *k).collect();
    ids.sort_by(|a, b| b.len().cmp(&a.len()));

    while !remaining.is_empty() {
        let mut found = false;
        for &id in &ids {
            if remaining.starts_with(id) {
                if let Some(xsampa) = lookup_phoneme(id) {
                    result.push(xsampa.to_string());
                }
                // All identifiers are ASCII, so byte-slicing is safe here
                remaining = &remaining[id.len()..];
                found = true;
                break;
            }
        }
        if !found {
            // Skip one character (safe with chars())
            if let Some(ch) = remaining.chars().next() {
                let ch_len = ch.len_utf8();
                remaining = &remaining[ch_len..];
            } else {
                break;
            }
        }
    }
    result
}

fn parse_pronunciation(pron: &str) -> Vec<String> {
    let mut result = Vec::new();
    let chars: Vec<char> = pron.chars().collect();
    let mut i = 0;
    let mut in_slash = false;
    let mut current = String::new();

    fn is_bare_marker(ch: char) -> bool {
        ch == '\'' || ch == ',' || ch == '_'
    }

    while i < chars.len() {
        let ch = chars[i];

        if ch == '/' {
            if in_slash {
                // Closing a slash group — flush accumulated content
                if !current.is_empty() {
                    let phonemes = split_slash_content(&current);
                    result.extend(phonemes);
                    current.clear();
                }
                i += 1;
                // Stay in slash mode for shared-slash convention, unless
                // next char is a bare marker
                if i >= chars.len() || is_bare_marker(chars[i]) {
                    in_slash = false;
                }
            } else {
                // Opening / — enter slash mode
                in_slash = true;
                current.clear();
                i += 1;
            }
        } else if in_slash {
            current.push(ch);
            i += 1;
        } else {
            match ch {
                '\'' | ',' => {
                    // Stress markers stripped
                }
                '_' => {
                    result.push("_".to_string());
                }
                _ => {
                    let ch_str = ch.to_string();
                    if let Some(xsampa) = lookup_phoneme(&ch_str) {
                        result.push(xsampa.to_string());
                    }
                }
            }
            i += 1;
        }
    }

    if in_slash && !current.is_empty() {
        let phonemes = split_slash_content(&current);
        result.extend(phonemes);
    }

    result
}